#!/usr/bin/env bash

# Debian packages
sudo aptitude update > /dev/null
sudo aptitude upgrade

# Hosts file
cd ~/opt/hblock/
git pull
./hblock

# Firefox preferences
cd ~/opt/user.js
./deploy

# File database
update-file-database
