#!/usr/bin/env bash

# Debian packages
sudo aptitude update > /dev/null
sudo aptitude upgrade

# Hosts file
cd ~/opt/hblock/
git pull
./hblock

# Firefox script
cd ~/opt/user.js
cp user.js ~/.mozilla/firefox/$(firefox-profile)/user.js -v

# File database
update-file-database
